---
# tasks file for wlan_ap

- name: Check if NetworkManager and Dnsmasq are installed
  yum: name={{ item }} state=present
  with_items:
   - NetworkManager
   - NetworkManager-wifi
   - dnsmasq
  tags:
   - nmcli
   - dnsmasq

- name: Check if wifi device exists and exit if not
  shell: nmcli device status | grep wifi
  register: nmcli_result
  ignore_errors: False
  tags: nmcli

- name: Assign wifi device name to variable
  shell: nmcli device status | grep wifi | cut -d" " -f1
  register: wlan_ap_device
  tags: nmcli

- name: Run nmcli to check if wifi access point connection has already been added
  shell: /usr/bin/nmcli c | grep {{ wlan_ap_ssid }}
  register: nmcli_result
  ignore_errors: True
  tags: nmcli

- name: Run nmcli to add a connection with the specified parameters as a wifi access point if above check has failed
  command: /usr/bin/nmcli c add autoconnect yes save yes con-name {{ wlan_ap_ssid }} ifname {{ wlan_ap_device }} type wifi ssid {{ wlan_ap_ssid }} mode ap ip4 {{ wlan_ap_ipaddress }}
  when: nmcli_result | failed
  tags: nmcli

- name: Run nmcli to add WPA-PSK security to the wifi connection
  command: /usr/bin/nmcli c mod {{ wlan_ap_ssid }} 802-11-wireless-security.key-mgmt wpa-psk 802-11-wireless-security.psk {{ wlan_ap_secret }} 802-11-wireless-security.pairwise ccmp, 802-11-wireless-security.proto rsn
  tags: nmcli

- name: Run nmcli to activate wifi access point connection
  command: /usr/bin/nmcli c up {{ wlan_ap_ssid }}
  tags: nmcli

- name: Add nmcli c up {{ wlan_ap_ssid }} to /etc/rc.local to workaround a bug in systemd
  shell: grep "nmcli c up {{ wlan_ap_ssid }}" /etc/rc.local || echo "/usr/bin/nmcli c up {{ wlan_ap_ssid }}" >> /etc/rc.local
  tags: nmcli

- name: Make /etc/rc.d/rc.local executable to enable the previous fix
  command: /usr/bin/chmod +x /etc/rc.d/rc.local
  tags: nmcli

# maybe add source={{ wlan_ap_ipaddress }} if ansible version >=2.0
- name: Insert firewalld rule for DNS port 52
  firewalld: service=dns permanent=true state=enabled immediate=yes
  tags: dnsmasq

- name: Insert firewalld rule for DHCP port 67
  firewalld: service=dhcp permanent=true state=enabled immediate=yes
  tags: dnsmasq

- name: Run firewall-cmd to add masquerading permanently
  command: /usr/bin/firewall-cmd --permanent --add-masquerade
  tags: dnsmasq

- name: Run firewall-cmd to add masquerading immediately (just to be sure it's actived in case the expected reboot is not happening)
  command: /usr/bin/firewall-cmd --add-masquerade
  tags: dnsmasq

- name: Configure Dnsmasq
  template: src=dnsmasq-wlan_ap.j2 dest=/etc/dnsmasq.d/dnsmasq-wlan_ap.conf
  tags: dnsmasq

- name: Enable and start Dnsmaq
  service: name=dnsmasq state=started enabled=yes
  tags: dnsmasq
